version: '3'
services:
  census-fsdr-ui:
    container_name: 'census-fsdr-ui'
    build: './'
    depends_on:
    - 'redis'
    ports:
    - '0.0.0.0:9293:9293'
    environment:
      REDIS_SERVER: 'redis'
      REDIS_PORT: '6379'
      APP_SETTINGS: 'DevelopmentConfig'
      PORT: '9293'
  redis:
    image: 'redis:alpine'
    ports:
    - '6379:6379'
    environment:
      POSTGRES_PASSWORD: 'password'
  idp:
    build: './local-idp-config'
    ports:
    - '0.0.0.0:8080:80'
    volumes:
    - ./local-idp-config/config_config.php:/var/simplesamlphp/config/config.php
    - ./local-idp-config/config_authsources.php:/var/simplesamlphp/config/authsources.php
    - ./local-idp-config/metadata_saml20-idp-hosted.php:/var/simplesamlphp/metadata/saml20-idp-hosted.php
    - ./local-idp-config/metadata_saml20-sp-remote.php:/var/simplesamlphp/metadata/saml20-sp-remote.php
    - ./local-idp-config/idp.crt:/var/simplesamlphp/cert/idp.crt
    - ./local-idp-config/idp.pem:/var/simplesamlphp/cert/idp.pem
 
